# Generated by Django 3.2.8 on 2021-12-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=1550)),
                ('before_picture', models.ImageField(blank=True, upload_to='before_picture/')),
                ('after_picture', models.ImageField(blank=True, upload_to='after_picture/')),
                ('display', models.BooleanField(default=True)),
            ],
        ),
    ]
