# Generated by Django 3.2.8 on 2021-12-19 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentdetails',
            options={'verbose_name_plural': 'Treatment Details'},
        ),
        migrations.RenameField(
            model_name='treatmentdetails',
            old_name='display',
            new_name='display_treatment',
        ),
        migrations.RenameField(
            model_name='treatmentdetails',
            old_name='description',
            new_name='treatment_description',
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to='main_picture/'),
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_a',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_b',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_c',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_d',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_name_a',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_name_b',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_name_c',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_name_d',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='treatment_price_description',
            field=models.CharField(blank=True, max_length=1550, null=True),
        ),
    ]
