# Generated by Django 3.2.8 on 2021-12-19 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_auto_20211219_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentdetails',
            name='main_picture',
            field=models.ImageField(upload_to='main_picture/'),
        ),
        migrations.AlterField(
            model_name='treatmentdetails',
            name='price_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='treatmentdetails',
            name='price_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='treatmentdetails',
            name='price_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='treatmentdetails',
            name='price_name_a',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentdetails',
            name='treatment_price_description',
            field=models.CharField(max_length=1550, null=True),
        ),
    ]
