# Generated by Django 3.2.8 on 2021-12-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_auto_20211219_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentdetails',
            name='treatment_price_description',
            field=models.CharField(blank=True, max_length=1550, null=True),
        ),
    ]
