# Generated by Django 3.2.8 on 2021-12-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0004_alter_treatmentdetails_treatment_price_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentdetails',
            name='price_name_b',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='treatmentdetails',
            name='price_name_c',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='treatmentdetails',
            name='price_name_d',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
