# Generated by Django 3.1.3 on 2022-05-27 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0006_auto_20211219_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_e',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_name_e',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_name_f',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_name_g',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='treatmentdetails',
            name='price_name_h',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='treatmentdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
