# Generated by Django 3.1.3 on 2022-05-27 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0007_auto_20220527_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentdetails',
            name='price_e',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
