# Generated by Django 3.2.8 on 2021-12-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description1', models.TextField(max_length=10000)),
                ('description2', models.TextField(max_length=10000)),
                ('description3', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='CarouselPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(blank=True, upload_to='carousel photos/')),
            ],
            options={
                'verbose_name_plural': 'Carousel Photos',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=254)),
                ('subheader', models.TextField(max_length=254)),
                ('telephone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('instagram_handle', models.URLField(blank=True, default='', max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Section',
            },
        ),
    ]
