# Generated by Django 3.1.3 on 2021-12-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='about',
            name='description2',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description3',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
