# Generated by Django 3.1.3 on 2021-12-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='instagram_handle',
            field=models.URLField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
