# Generated by Django 3.1.3 on 2021-12-08 14:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_carouselphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselphoto',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
