# Generated by Django 3.1.3 on 2021-12-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_remove_carouselphoto_friendly_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='carousel photos/'),
        ),
    ]
